# Copyright (c) 2026, Omnexa and contributors
# License: See license.txt

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt

from omnexa_education.billing import calculate_discount_amount, calculate_late_fee_amount


class EducationBillingCycle(Document):
	def validate(self):
		self._validate_branch_company_match()
		self._validate_links_company()
		self._validate_installment_no()

	def on_submit(self):
		self._generate_invoices()

	def _validate_branch_company_match(self):
		branch_company = frappe.db.get_value("Branch", self.branch, "company")
		if not branch_company:
			frappe.throw(_("Branch {0} does not exist.").format(self.branch), title=_("Branch"))
		if branch_company != self.company:
			frappe.throw(_("Branch belongs to a different company."), title=_("Branch"))

	def _validate_links_company(self):
		for doctype, field in (
			("Education Academic Year", "academic_year"),
			("Education Fee Plan", "fee_plan"),
		):
			name = self.get(field)
			if not name:
				continue
			co = frappe.db.get_value(doctype, name, "company")
			if co and co != self.company:
				frappe.throw(_("{0} must belong to the same company.").format(doctype), title=_("Company"))
		if self.discount_rule:
			co = frappe.db.get_value("Education Discount Rule", self.discount_rule, "company")
			if co and co != self.company:
				frappe.throw(_("Discount Rule must belong to the same company."), title=_("Company"))
		if self.late_fee_rule:
			co = frappe.db.get_value("Education Late Fee Rule", self.late_fee_rule, "company")
			if co and co != self.company:
				frappe.throw(_("Late Fee Rule must belong to the same company."), title=_("Company"))

	def _validate_installment_no(self):
		if int(self.installment_no or 1) < 1:
			frappe.throw(_("Installment No must be at least 1."), title=_("Installment"))

	def _generate_invoices(self):
		plan = frappe.get_doc("Education Fee Plan", self.fee_plan)
		if not plan.is_active:
			frappe.throw(_("Selected fee plan is inactive."), title=_("Fee Plan"))
		discount_rule = frappe.get_doc("Education Discount Rule", self.discount_rule).as_dict() if self.discount_rule else None
		late_rule = frappe.get_doc("Education Late Fee Rule", self.late_fee_rule).as_dict() if self.late_fee_rule else None
		late_fee_item = (
			frappe.get_doc("Education Fee Item", late_rule.get("late_fee_item")).as_dict()
			if late_rule and late_rule.get("late_fee_item")
			else None
		)

		students = self._get_target_students()
		gen = 0
		fail = 0
		for s in students:
			try:
				items = []
				for p in plan.items or []:
					fee = frappe.get_doc("Education Fee Item", p.fee_item).as_dict()
					qty = flt(p.qty) or 1
					rate = flt(p.rate) or flt(fee.get("default_rate"))
					if fee.get("is_recurring") and int(plan.installments_count or 1) > 1:
						rate = flt(rate / int(plan.installments_count))
					base_amount = flt(qty) * flt(rate)
					disc = calculate_discount_amount(base_amount, fee, discount_rule, self.posting_date)
					final_amount = max(0.0, flt(base_amount - disc))
					final_rate = flt(final_amount / qty) if qty else 0
					items.append(
						{
							"fee_item": fee.get("name"),
							"description": p.description or fee.get("fee_name"),
							"qty": qty,
							"rate": final_rate,
							"tax_rule": p.tax_rule if hasattr(p, "tax_rule") else None,
						}
					)

				late_amt = calculate_late_fee_amount(
					customer=s.customer, posting_date=self.posting_date, late_fee_rule_doc=late_rule
				)
				if late_amt > 0 and late_fee_item:
					items.append(
						{
							"fee_item": late_fee_item.get("name"),
							"description": late_fee_item.get("fee_name") or _("Late Fee"),
							"qty": 1,
							"rate": late_amt,
						}
					)

				if not items:
					continue
				inv = frappe.get_doc(
					{
						"doctype": "Education Billing Invoice",
						"naming_series": "EDINV-.#####",
						"company": self.company,
						"branch": self.branch,
						"student": s.name,
						"posting_date": self.posting_date,
						"due_date": self.due_date,
						"currency": plan.currency,
						"conversion_rate": 1,
						"items": items,
						"remarks": _("Generated by Billing Cycle {0}").format(self.name),
					}
				).insert(ignore_permissions=True)
				if self.submit_invoices:
					inv.submit()
				gen += 1
			except Exception:
				fail += 1
				frappe.log_error(frappe.get_traceback(), f"Billing Cycle row failed: {self.name}")

		self.db_set("generated_count", gen, update_modified=False)
		self.db_set("failed_count", fail, update_modified=False)

	def _get_target_students(self):
		filters = {"company": self.company, "branch": self.branch, "status": "Active"}
		if self.campus_filter:
			filters["campus"] = self.campus_filter
		if self.section_filter:
			filters["section"] = self.section_filter
		return frappe.get_all(
			"Education Student",
			filters=filters,
			fields=["name", "student_name", "customer"],
			order_by="modified asc",
		)

