# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""One-shot bootstrap for EduSphere ↔ Laravel Eschools integration."""

from __future__ import annotations

import os
from pathlib import Path

import frappe
from frappe import _
from frappe.utils import get_url, now_datetime

from omnexa_education.api import laravel_client
from omnexa_education.api.education_unified_inbox import create_portal_message
from omnexa_education.api.laravel_integration_e2e import run_laravel_integration_e2e
from omnexa_education.api.laravel_sync import sync_institution_full_to_laravel
from omnexa_education.api.parent_account_lifecycle import provision_parent
from omnexa_education.api.portal_validation import validate_all_portals
from omnexa_education.api.teacher_account_lifecycle import bulk_provision_teachers

DEFAULT_LARAVEL_URL = "https://kemetgate.com"
DEFAULT_API_KEY = "edusphere-demo-api-key-2026"
DEFAULT_WEBHOOK_SECRET = "edusphere-webhook-secret-2026"
DEFAULT_JWT_SECRET = "edusphere-jwt-shared-secret-2026"

MH_INSTITUTIONS = [
	"MH-EDU-DEMO-UNIV",
	"MH-EDU-DEMO-INTSCH",
	"MH-EDU-DEMO-ACADIT",
	"MH-EDU-DEMO-INST",
	"MH-EDU-DEMO-TRAIN",
]


def _write_laravel_env_snippet(
	laravel_base_url: str,
	api_key: str,
	webhook_secret: str,
	jwt_secret: str,
) -> str | None:
	root = Path(frappe.get_app_path("omnexa_education")).parents[2] / "LMS" / "Eschools"
	if not root.exists():
		return None
	webhook_url = get_url("/api/method/omnexa_education.api.laravel_webhooks.receive")
	content = f"""# Generated by ErpGenEx bootstrap — {now_datetime()}
ERPGENEX_ENABLED=true
ERPGENEX_BASE_URL={get_url().rstrip('/')}
ERPGENEX_WEBHOOK_URL={webhook_url}
ERPGENEX_WEBHOOK_SECRET={webhook_secret}
ERPGENEX_API_KEY={api_key}
ERPGENEX_TENANT_HEADER=X-ErpGenEx-School
JWT_SECRET={jwt_secret}
ERPGENEX_JWT_SECRET={jwt_secret}
ALLOW_READONLY_ON_HOLD=false
ERPGENEX_DEFAULT_STUDENT_PASSWORD=Education@Demo2026
"""
	out = root / ".env.erpgenex.integration"
	out.write_text(content, encoding="utf-8")
	return str(out)


def _configure_education_settings(
	laravel_base_url: str,
	api_key: str,
	webhook_secret: str,
	jwt_secret: str,
	enable: bool = True,
) -> dict:
	settings = frappe.get_single("Education Settings")
	settings.enable_laravel_tlms = 1 if enable else 0
	settings.laravel_base_url = laravel_base_url.rstrip("/")
	settings.laravel_api_key = api_key
	settings.laravel_webhook_secret = webhook_secret
	settings.laravel_jwt_secret = jwt_secret
	settings.laravel_sso_enabled = 1 if enable else 0
	settings.auto_provision_parent_user = 1
	settings.auto_sync_enrollments_on_submit = 1
	settings.laravel_institution_header = settings.laravel_institution_header or "X-ErpGenEx-School"
	settings.save(ignore_permissions=True)
	return {
		"enable_laravel_tlms": bool(settings.enable_laravel_tlms),
		"laravel_base_url": settings.laravel_base_url,
		"webhook_url": get_url("/api/method/omnexa_education.api.laravel_webhooks.receive"),
	}


def _provision_all_parents() -> dict:
	emails = frappe.get_all(
		"Education Student",
		filters={"guardian_email": ["is", "set"], "status": "Active"},
		pluck="guardian_email",
		distinct=True,
	)
	ok = 0
	failed = 0
	skipped = 0
	for email in emails:
		if frappe.db.get_value(
			"Education Student",
			{"guardian_email": email, "guardian_laravel_user_id": ["is", "set"]},
			"name",
		):
			skipped += 1
			continue
		try:
			provision_parent(email, trigger="System")
			ok += 1
		except Exception:
			failed += 1
			frappe.log_error(frappe.get_traceback(), f"Parent bootstrap failed: {email}")
	return {"parents_ok": ok, "parents_failed": failed, "parents_skipped": skipped, "unique_emails": len(emails)}


def _seed_demo_inbox() -> int:
	count = 0
	student = frappe.db.get_value("Education Student", {"status": "Active"}, "name")
	if not student:
		return 0
	samples = [
		("Welcome to EduSphere", "Your unified portal is ready.", "Administrative"),
		("Midterm schedule published", "Review the academic calendar for exam dates.", "Academic"),
		("Fee reminder", "Please settle outstanding invoices before the due date.", "Financial"),
	]
	for title, body, channel in samples:
		if frappe.db.exists("Education Portal Message", {"title": title, "student": student}):
			continue
		create_portal_message(title, body, channel=channel, student=student)
		count += 1
	return count


@frappe.whitelist()
def bootstrap_laravel_integration(
	laravel_base_url: str | None = None,
	api_key: str | None = None,
	webhook_secret: str | None = None,
	jwt_secret: str | None = None,
	provision_accounts: int = 1,
	full_sync: int = 1,
	institutions: str | None = None,
) -> dict:
	"""Configure keys, provision accounts, sync institutions, validate."""
	frappe.only_for(("System Manager", "Education Manager"))

	laravel_base_url = (
		laravel_base_url
		or os.environ.get("LARAVEL_BASE_URL")
		or os.environ.get("ERPGENEX_LARAVEL_URL")
		or DEFAULT_LARAVEL_URL
	)
	api_key = api_key or os.environ.get("ERPGENEX_API_KEY") or DEFAULT_API_KEY
	webhook_secret = webhook_secret or os.environ.get("ERPGENEX_WEBHOOK_SECRET") or DEFAULT_WEBHOOK_SECRET
	jwt_secret = jwt_secret or os.environ.get("JWT_SECRET") or os.environ.get("ERPGENEX_JWT_SECRET") or DEFAULT_JWT_SECRET

	config = _configure_education_settings(laravel_base_url, api_key, webhook_secret, jwt_secret)
	env_file = _write_laravel_env_snippet(laravel_base_url, api_key, webhook_secret, jwt_secret)

	parents = {"parents_ok": 0, "parents_failed": 0}
	teachers = {"provisioned": 0}
	if provision_accounts:
		frappe.flags.in_import = True
		try:
			parents = _provision_all_parents()
			teachers = bulk_provision_teachers()
		finally:
			frappe.flags.in_import = False

	sync_results = []
	inst_list = [i.strip() for i in (institutions or "").split(",") if i.strip()] or MH_INSTITUTIONS
	institutions_sync = {}
	if full_sync:
		from omnexa_education.api.laravel_sync import sync_institutions_to_laravel

		institutions_sync = sync_institutions_to_laravel(inst_list)
		for inst in inst_list:
			if frappe.db.exists("Education Institution", inst):
				try:
					sync_results.append(sync_institution_full_to_laravel(inst))
				except Exception as exc:
					sync_results.append({"institution": inst, "ok": False, "error": str(exc)[:200]})
					frappe.log_error(frappe.get_traceback(), f"Laravel full sync failed: {inst}")

	ping = laravel_client.ping()
	inbox_seeded = _seed_demo_inbox()
	portals = validate_all_portals()
	e2e = run_laravel_integration_e2e(institution=inst_list[0] if inst_list else None)

	return {
		"ok": portals.get("portal_score") == 100.0 and e2e.get("ok"),
		"config": config,
		"laravel_env_snippet": env_file,
		"ping": ping,
		"parents": parents,
		"teachers": teachers,
		"sync": sync_results,
		"institutions_sync": institutions_sync,
		"inbox_seeded": inbox_seeded,
		"portals": {"score": portals.get("portal_score"), "pages_ok": portals.get("pages_ok")},
		"e2e": {"passed": e2e.get("passed"), "total": e2e.get("total")},
		"institutions": inst_list,
		"laravel_next_steps": [
			"On kemetgate.com: merge .env.erpgenex.integration into .env (ERPGENEX_ENABLED=true)",
			"Deploy Laravel with institutions/sync API (git pull + php artisan route:cache)",
			"Set ERPGENEX_BASE_URL to your public ErpGenEx URL for webhooks",
			"Re-run bootstrap from /app/education-laravel-integration",
		],
	}


@frappe.whitelist()
def connect_kemetgate_laravel(full_sync: int = 1, provision_accounts: int = 0) -> dict:
	"""Configure EduSphere ↔ kemetgate.com Eschools and run integration bootstrap."""
	return bootstrap_laravel_integration(
		laravel_base_url="https://kemetgate.com",
		full_sync=full_sync,
		provision_accounts=provision_accounts,
	)


def execute_bootstrap():
	"""bench execute entrypoint."""
	return bootstrap_laravel_integration()
